# Generated by Django 3.0 on 2022-11-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('first_salary', models.CharField(max_length=255)),
                ('ex_workplace', models.CharField(max_length=255)),
                ('leisure_activities', models.CharField(max_length=255)),
                ('achievements', models.CharField(max_length=600)),
                ('ex_salary', models.CharField(max_length=255)),
                ('expected_salary', models.CharField(max_length=255)),
                ('start_salary', models.CharField(max_length=255)),
                ('salary_factor', models.CharField(max_length=600)),
                ('best_employee', models.CharField(max_length=255)),
                ('marital_status', models.CharField(max_length=255)),
                ('book', models.CharField(max_length=600)),
                ('bad_habit', models.CharField(max_length=600)),
                ('work_achievements', models.CharField(max_length=600)),
                ('ready_to_start', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Candidates',
            },
        ),
    ]
