# Generated by Django 3.0 on 2022-11-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20221109_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
