# Generated by Django 3.0 on 2022-11-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_candidate_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='step',
            field=models.IntegerField(default=0),
        ),
    ]
