# Generated by Django 3.0 on 2022-11-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_candidate_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='on_process',
            field=models.BooleanField(default=False),
        ),
    ]
